### ISSUE TITLE
trackPage option should track route changes

### ISSUE THREAD

**Issue by seaneking** [benjaminhoffman/gatsby-plugin-segment-js#6] opened 2018-09-11 11:36 UTC
Is there a reason why the `trackPage` option only calls `analtyics.page()` once on initial render, and not on every route change? Seems kinda redundant, and should definitely be documented if nothing else.

**Comment by benjaminhoffman** [comment] 2018-09-11 16:38
the `trackPage` option allows for you to include (`true`) or exclude (`false`) the `analytics.page()` call in your Segment snippet.  if you include it, the snippet will follow "normal" segment snippet behavior and fire on every page load.  if you exclude it, you will have to fire it manually.

generally, you will want to exclude it if you are using a SPA (like react or gatsby) and will want to fire page calls manually.  the reason is because SPA's dont have page loads on each navigation change.

this is normal and expected behavior of segment and SPAs, and has nothing to do with this gatsby plugin.

read this post for more info: https://medium.com/@benhoffman/how-to-install-segment-io-javascript-into-a-react-redux-web-app-649b26ea0e65

going to close out this issue for now but feel free to comment or re-open if the above does not address your question. thx.

**Comment by seaneking** [comment] 2018-09-11 20:43
Yep I get that, but this plugin is specifically for Gatsby, which has a canonical way to update things on route change. So it seems a little pointless to have a config option like this without taking advantage of that.

If nothing else that decision should be documented. Coming at this I'd intuitively expect `trackPages` to leverage Gatsby in order to track pages.

**Comment by benjaminhoffman** [comment] 2018-09-11 20:53
that's a good point... maybe i'll change this to `trackPagesWithGatsby` where it fires a track page call on route change using Gatsby.  otherwise, user can invoke the page call themselves.

re-opening this issue for now.  

interested in opening a PR @seaneking ?  shouldn't be too difficult.

**Comment by seaneking** [comment] 2018-09-12 07:47
Sure thing, will submit a PR when I get a moment later today. To clarify, do you want a breaking change to rename that option? IMO the current one is explicit enough, and can always add a note to the readme to clarify further

**Comment by seaneking** [comment] 2018-09-12 13:46
https://github.com/benjaminhoffman/gatsby-plugin-segment-js/pull/7

**Comment by biw** [comment] 2018-11-16 00:53
Just wanted to follow up on this to say that it would awesome to get #7 merged. 😄 

If I can add my 2 cents, it would probably need to be a breaking change as I'm sure other people have done the same code that you added on #7 and just pushing would result in a double fire of the event.

What do you think @seaneking & @benjaminhoffman?

**Comment by benjaminhoffman** [comment] 2018-12-25 08:10
okay i will merge and re-deploy.  it is definitely a breaking change and will bump the major version

**Closed by benjaminhoffman** 2018-12-25 08:10 UTC

**Comment by benjaminhoffman** [comment] 2019-02-16 18:00
This is done.  But I did have to make a slight modification since `trackPage` was being called twice.  Thanks for the solution!
